export type ResourceSection = {
  heading: string;
  paragraphs?: string[];
  bullets?: string[];
};

export type ResourcePage = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  answer: string;
  updated: string;
  cluster: 'rash-guard' | 'training-shorts' | 'grappling-shorts' | 'project';
  media?: Array<{ src: string; alt: string; caption: string }>;
  table: Array<[string, string]>;
  decisionRows: Array<[choice: string, bestFor: string, buyerCheck: string]>;
  notFor: string[];
  source: string;
  sections: ResourceSection[];
  faqs?: Array<[question: string, answer: string]>;
  relatedProduct: { label: string; href: string };
  relatedGuides?: string[];
};

export const RESOURCE_PAGES: ResourcePage[] = [
  {
    slug: 'rash-guard-fabric-construction',
    title: 'Rash Guard Fabric & Construction Guide',
    description: 'A buyer guide to rash guard fabric weight, composition, opacity, stretch, sublimation and silicone anti-slip hems.',
    eyebrow: 'RASH GUARD BUYER GUIDE',
    answer: 'A dependable custom Rash Guard specification connects fabric weight, composition, opacity, stretch recovery, seam construction and hem control. Selected TONTON styles use 220gsm ultra-fine Lycra; the Blue Team and White Pro Club examples use 85% polyester and 15% spandex with a silicone anti-slip elastic band.',
    updated: '2026-09-15',
    cluster: 'rash-guard',
    media: [
      { src: '/assets/products/rash-guard-products/construction-details/stretch-fabric-seam.webp', alt: 'Close-up of stretch Rash Guard fabric and parallel seam construction', caption: 'Stretch fabric surface and multi-row seam construction on the real sample.' },
      { src: '/assets/products/rash-guard-products/construction-details/breathable-mesh-panel.webp', alt: 'Close-up of breathable mesh panel joined to Rash Guard fabric', caption: 'Breathable mesh inset with a clean stitched transition between panels.' },
      { src: '/assets/products/rash-guard-products/construction-details/reinforced-seam-junction.webp', alt: 'Close-up of reinforced Rash Guard seam intersection', caption: 'Reinforced seam intersection at a high-movement panel junction.' },
    ],
    table: [
      ['Example fabric weight', '220gsm ultra-fine Lycra'],
      ['Verified composition', '85% polyester / 15% spandex on selected styles'],
      ['Coverage direction', 'Opaque under stretch; reconfirmed on the approved sample'],
      ['Decoration', 'Sublimation-ready panel artwork'],
      ['Hem option', 'Silicone anti-slip elastic band'],
      ['Typical use', 'BJJ, MMA, grappling and team training'],
    ],
    decisionRows: [
      ['220gsm ultra-fine Lycra', 'Buyers prioritizing soft hand feel, strong stretch and opaque coverage', 'Confirm opacity, recovery and fit on the approved sample'],
      ['85% polyester / 15% spandex', 'Sublimated team graphics on selected verified styles', 'Confirm the composition belongs to the selected style'],
      ['Silicone anti-slip hem', 'Close-fit training where lower-hem movement needs more control', 'Review grip feel and placement during movement'],
    ],
    notFor: [
      'Do not select a fabric from GSM alone; weight does not prove opacity, recovery or comfort.',
      'Do not assume every TONTON Rash Guard uses the same composition or hem construction.',
      'Do not approve bulk production before checking the intended fit and artwork on the physical sample.',
    ],
    source: 'TONTON approved product specifications for selected 220gsm Rash Guard styles and physical sample review criteria.',
    sections: [
      { heading: 'Why fabric weight and opacity should be reviewed together', paragraphs: ['Fabric weight alone does not confirm how a garment performs when stretched. Buyers should review weight, hand feel, recovery and opacity on the same approved sample, under the intended fit direction.'] },
      { heading: 'What the polyester-spandex blend contributes', paragraphs: ['On the verified 85/15 styles, polyester provides a smooth surface suited to sublimated graphics, while spandex provides the stretch required for a close performance fit.'] },
      { heading: 'Construction details worth specifying', bullets: ['Sleeve length and raglan panel direction', 'Seam placement and stretch compatibility', 'Lower-hem grip requirement', 'Logo, sponsor mark and panel-artwork positions', 'Size range, fit direction, private labels and packaging'] },
    ],
    relatedProduct: { label: 'View the Blue Team 220gsm Rash Guard', href: '/products/blue-team-rash-guard' },
    relatedGuides: ['220gsm-rash-guard-fabric-guide', 'flatlock-vs-overlock-rash-guard-seams', 'rash-guard-silicone-anti-slip-band', 'rash-guard-sublimation-logo-placement'],
  },
  {
    slug: '220gsm-rash-guard-fabric-guide',
    title: '220gsm Rash Guard Fabric: Weight, Stretch & Opacity',
    description: 'How buyers should evaluate 220gsm Rash Guard fabric for hand feel, stretch recovery, opacity and sublimated performance wear.',
    eyebrow: 'RASH GUARD MATERIAL GUIDE',
    answer: 'A 220gsm fabric can provide a substantial, soft and opaque Rash Guard direction, but GSM alone is not a quality guarantee. Buyers should assess fabric composition, four-way movement, recovery, opacity under the intended fit, print surface and seam compatibility on the same physical sample.',
    updated: '2026-09-15',
    cluster: 'rash-guard',
    table: [
      ['Verified example', '220gsm ultra-fine Lycra'],
      ['Selected composition', '85% polyester / 15% spandex on the Blue Team and White Pro styles'],
      ['Buyer priorities', 'Soft hand feel, elasticity, recovery and opaque coverage'],
      ['Print direction', 'Sublimation-compatible polyester surface on the verified 85/15 styles'],
      ['Sample test', 'Stretch the garment at chest, shoulder and torso fit points'],
      ['Use direction', 'BJJ, MMA, grappling and close-fit team training'],
    ],
    decisionRows: [
      ['220gsm direction', 'Programs prioritizing substantial coverage and a close performance fit', 'Compare hand feel, recovery and heat management on the sample'],
      ['Verified 85/15 blend', 'Selected styles requiring detailed sublimated graphics', 'Confirm the chosen SKU uses this exact composition'],
      ['Lighter fabric direction', 'Projects prioritizing lower weight over the verified 220gsm feel', 'Request a separate sample; do not infer performance from GSM alone'],
    ],
    notFor: ['Do not use 220gsm as a universal specification for every Rash Guard style.', 'Do not call fabric opaque until it has been checked under the intended stretch and fit.', 'Do not reuse the verified 85/15 composition for a product whose composition has not been confirmed.'],
    source: 'TONTON selected 220gsm Rash Guard specifications and physical-sample evaluation criteria.',
    sections: [
      { heading: 'What 220gsm tells a buyer—and what it does not', paragraphs: ['GSM describes fabric mass per square metre. It helps compare weight directions, but it does not independently prove softness, opacity, breathability or recovery. Those qualities need to be checked together on the selected material.'] },
      { heading: 'A practical opacity and recovery check', bullets: ['Evaluate the fabric at the intended body fit', 'Stretch printed and solid-color areas under consistent light', 'Check whether the fabric returns smoothly after extension', 'Review shoulder, chest and torso zones where strain is highest'] },
      { heading: 'Connect material approval to the finished garment', paragraphs: ['Approve the fabric together with seam direction, sleeve construction, lower-hem control and artwork placement. This prevents an acceptable fabric swatch from becoming a poorly balanced finished Rash Guard.'] },
    ],
    relatedProduct: { label: 'Compare the 220gsm Rash Guard sample', href: '/products/blue-team-rash-guard' },
    relatedGuides: ['rash-guard-fabric-construction', 'rash-guard-silicone-anti-slip-band'],
  },
  {
    slug: 'rash-guard-silicone-anti-slip-band',
    title: 'Rash Guard Silicone Anti-Slip Band Guide',
    description: 'A buyer guide to silicone anti-slip elastic bands, lower-hem control, placement and sample checks for custom Rash Guards.',
    eyebrow: 'RASH GUARD CONSTRUCTION GUIDE',
    answer: 'A silicone anti-slip elastic band is an interior lower-hem option designed to add grip and reduce ride-up during movement. Buyers should confirm band width, grip feel, stretch compatibility, seam finish and comfort on the worn sample rather than approving the component in isolation.',
    updated: '2026-09-15',
    cluster: 'rash-guard',
    table: [['Component', 'Interior silicone anti-slip elastic band'], ['Position', 'Inside the lower Rash Guard hem'], ['Purpose', 'Add hem control during grappling and repeated movement'], ['Confirm', 'Width, placement, grip feel, stretch and seam comfort'], ['Related fit', 'Close performance fit'], ['Approval', 'Movement test on the physical sample']],
    decisionRows: [['Silicone grip band', 'Training where lower-hem stability is a priority', 'Check grip without excessive pressure or irritation'], ['Standard stretch hem', 'Projects preferring a simpler lower edge', 'Compare ride-up and recovery during movement'], ['Coordinated set', 'Rash Guard and shorts programs sharing visual direction', 'Approve each garment’s waist and hem system separately']],
    notFor: ['Do not describe a silicone band as preventing all garment movement.', 'Do not choose maximum grip without considering comfort and stretch.', 'Do not assume the option is included on every style.'],
    source: 'TONTON selected Rash Guard sample details showing an interior silicone anti-slip elastic band.',
    sections: [{ heading: 'Why lower-hem control matters', paragraphs: ['Grappling, framing and repeated torso rotation can pull a close-fit top upward. An interior grip band adds contact at the hem, helping the garment remain more stable through movement.'] }, { heading: 'What to put in the product brief', bullets: ['Required band width and position', 'Preferred grip intensity and hand feel', 'Hem circumference and stretch requirement', 'Seam finish at the band edge', 'Intended sport and fit direction'] }, { heading: 'How to approve the sample', paragraphs: ['Test the hem while reaching, rotating, sprawling and returning to stance. Review stability, pressure, comfort and whether the band recovers with the surrounding fabric.'] }],
    relatedProduct: { label: 'View a Rash Guard with anti-slip hem', href: '/products/white-logo-rash-guard' },
    relatedGuides: ['rash-guard-fabric-construction', '220gsm-rash-guard-fabric-guide', 'prepare-artwork-for-sublimation'],
  },
  {
    slug: 'flatlock-vs-overlock-rash-guard-seams',
    title: 'Flatlock vs Overlock Seams for Rash Guards',
    description: 'Compare flatlock and overlock seam directions for custom Rash Guards, including profile, stretch, comfort, reinforcement and sample approval checks.',
    eyebrow: 'RASH GUARD SEAM GUIDE',
    answer: 'Flatlock and overlock are different seam directions, not interchangeable quality labels. Flatlock can create a lower-profile seam against the body, while overlock joins cut edges efficiently and may be combined with cover stitching or reinforcement. The right choice depends on panel position, stretch, skin contact, intended use and the approved physical sample.',
    updated: '2026-09-22',
    cluster: 'rash-guard',
    media: [
      { src: '/assets/products/rash-guard-products/construction-details/stretch-fabric-seam.webp', alt: 'Close-up of stretch Rash Guard fabric with parallel seam construction', caption: 'Real sample close-up showing a stretch-compatible multi-row seam.' },
      { src: '/assets/products/rash-guard-products/construction-details/reinforced-seam-junction.webp', alt: 'Reinforced Rash Guard seam junction on a real garment sample', caption: 'Panel junction where seam profile, reinforcement and stretch must work together.' },
    ],
    table: [
      ['Flatlock direction', 'Lower-profile seam with thread visible across the joined edges'],
      ['Overlock direction', 'Joined cut edges; may be paired with cover stitching or topstitching'],
      ['Primary checks', 'Profile, stretch, recovery, abrasion and seam comfort'],
      ['High-movement zones', 'Shoulders, underarms, side panels and torso junctions'],
      ['Approval method', 'Inside and outside inspection plus worn movement test'],
      ['Final control', 'Record seam type and position in the approved specification'],
    ],
    decisionRows: [
      ['Flatlock direction', 'Close-fit panels where a lower seam profile is preferred', 'Check stretch, thread coverage and comfort against skin'],
      ['Overlock + cover direction', 'Efficient panel joining with a controlled outer finish', 'Confirm bulk, recovery and the exact cover-stitch route'],
      ['Reinforced junction', 'High-load panel intersections and repeated movement zones', 'Inspect backtacking, thread tension and stretch compatibility'],
    ],
    notFor: ['Do not call every visible multi-row seam flatlock without checking the reverse construction.', 'Do not select a seam only by appearance; thread, fabric and panel direction affect performance.', 'Do not approve seam comfort from a flat sample without a worn movement test.'],
    source: 'TONTON physical Rash Guard sample review and production checks for stretch seams, panel junctions and close-contact construction.',
    sections: [
      { heading: 'Understand the construction before naming it', paragraphs: ['A finished seam can look similar from the outside while using a different joining method underneath. Buyers should review both sides of the garment and record the actual stitch direction used at each panel.'] },
      { heading: 'Match seam direction to the body zone', bullets: ['Use a low-profile direction where the garment stays close to skin', 'Review underarm and shoulder stretch through full reach', 'Reinforce panel junctions without creating a hard contact point', 'Keep thread and stitch density compatible with fabric recovery'] },
      { heading: 'Approve the complete seam system', paragraphs: ['Inspect skipped stitches, waviness, exposed cut edges, thread tension and recovery. Then wear-test reaching, rotation and grappling movement before bulk approval.'] },
    ],
    faqs: [
      ['Is flatlock always better for a Rash Guard?', 'No. Flatlock can offer a low-profile direction, but the best construction depends on the panel, fabric, thread, intended fit and approved sample.'],
      ['Can overlock be used on stretch performance fabric?', 'Yes. It can join stretch panels effectively when stitch balance, thread and reinforcement are specified for the material and use.'],
      ['How should buyers confirm a seam type?', 'Review the inside and outside construction, identify the stitch route in the specification and approve it through a worn movement test.'],
    ],
    relatedProduct: { label: 'Explore custom Rash Guards', href: '/customization/sublimated-rash-guards' },
    relatedGuides: ['rash-guard-fabric-construction', '220gsm-rash-guard-fabric-guide', 'fightwear-quality-inspection-checklist'],
  },
  {
    slug: 'rash-guard-sublimation-logo-placement',
    title: 'Rash Guard Sublimation & Logo Placement Guide',
    description: 'Plan custom Rash Guard panel artwork, sponsor logos, scale and placement for a cleaner sublimated sample and repeatable production brief.',
    eyebrow: 'RASH GUARD ARTWORK GUIDE',
    answer: 'Effective Rash Guard artwork is designed around the garment panels, seams and stretch zones. Supply vector logos where possible, identify priority marks, define front, back and sleeve positions, and approve scale and distortion on a worn sample before bulk production.',
    updated: '2026-09-15',
    cluster: 'rash-guard',
    table: [['Decoration direction', 'Sublimated panel artwork'], ['Artwork input', 'Vector logos preferred where available'], ['Priority positions', 'Chest, sleeves, back and back neck'], ['Buyer check', 'Scale, contrast, seam crossing and stretch distortion'], ['Sample review', 'Flat view plus worn movement view'], ['Production control', 'Approved mockup and product specification']],
    decisionRows: [['Large panel artwork', 'Bold collection graphics and team identity', 'Check continuity across seams and size grading'], ['Focused logo system', 'Cleaner brand and sponsor hierarchy', 'Confirm minimum readable size and contrast'], ['Mixed solid and printed panels', 'Balancing clarity with visual impact', 'Approve panel boundaries and color consistency']],
    notFor: ['Do not place critical text directly across a seam without reviewing distortion.', 'Do not rely on a screen mockup to prove printed color or worn placement.', 'Do not enlarge every sponsor mark equally; define a visual hierarchy.'],
    source: 'TONTON Rash Guard mockup workflow and real sample review of chest, sleeve, back and neck branding positions.',
    sections: [{ heading: 'Design to the panel map', paragraphs: ['The front, back, sleeve and side panels behave differently when worn. Artwork should respect seam boundaries and reserve cleaner zones for names, sponsor marks and small text.'] }, { heading: 'Prepare production-ready artwork', bullets: ['Provide vector logo files where available', 'Name required colors or supply brand references', 'List priority and secondary marks', 'Show intended placement rather than sending an unstructured logo folder', 'Identify artwork that must remain aligned across panels'] }, { heading: 'Approve the worn result', paragraphs: ['Review artwork from front, back and side angles while the garment is on-body. Check scale, readability, stretch distortion and whether the brand hierarchy remains clear across the requested size range.'] }],
    relatedProduct: { label: 'Inspect a full graphic Rash Guard', href: '/products/samurai-graphic-rash-guard' },
    relatedGuides: ['rash-guard-fabric-construction', '220gsm-rash-guard-fabric-guide'],
  },
  {
    slug: 'high-split-grappling-shorts-specifications',
    title: 'High-Split Grappling Shorts Specification Guide',
    description: 'How to specify 2-in-1 grappling shorts with an ultra-high split, four-way stretch shell and supportive compression liner.',
    eyebrow: 'GRAPPLING SHORTS BUYER GUIDE',
    answer: 'A high-split 2-in-1 grappling short should balance unrestricted leg clearance with secure inner-layer coverage. TONTON’s current sample combines a breathable quick-dry four-way stretch shell, ultra-high gladiator split and a soft 250gsm milk-silk compression liner.',
    updated: '2026-09-15',
    cluster: 'grappling-shorts',
    table: [
      ['Silhouette', 'Athletic 2-in-1 construction'],
      ['Outer layer', 'Breathable, quick-dry four-way stretch'],
      ['Inner layer', '250gsm milk-silk compression liner'],
      ['Side cut', 'Ultra-high split, gladiator style'],
      ['Waist control', 'Drawstring plus anti-slip silicone grip strip'],
      ['Finishing', 'Reinforced stitching and tagless printed label'],
    ],
    decisionRows: [
      ['Ultra-high split', 'High kicks, shots, sprawls and wide grappling positions', 'Check split height and coverage during sport-specific movement'],
      ['Four-way stretch outer shell', 'Fast transitions and functional training', 'Confirm stretch recovery, breathability and quick-dry direction'],
      ['250gsm compression liner', 'Buyers requiring support, coverage and printable inner artwork', 'Review liner length, hand feel, opacity and seam comfort'],
    ],
    notFor: [
      'A very high split may not suit buyers who prefer a conservative outer silhouette.',
      'Do not approve liner artwork without checking stretch distortion and placement on a sample.',
      'Do not treat the 250gsm liner specification as universal across unrelated shorts styles.',
    ],
    source: 'TONTON High-Split 2-in-1 Grappling Shorts approved construction brief and real sample-detail review.',
    sections: [
      { heading: 'Mobility without losing coverage', paragraphs: ['The outer split releases the thigh for high kicks, shots, sprawls and wide grappling positions. The fitted liner stays closer to the body to provide support and coverage through those movements.'] },
      { heading: 'What buyers can customize', bullets: ['Inner-liner patterns and artwork', 'Outer-shell logos and sponsor marks', 'Waistband branding and drawstring direction', 'Split height, fit and size range on the approved sample', 'Tagless label and packaging requirements'] },
      { heading: 'Recommended sample checks', paragraphs: ['Review waistband stability, split height, liner coverage, stretch recovery, reinforced seams and graphic placement during sport-specific movement before bulk production is approved.'] },
    ],
    relatedProduct: { label: 'View the High-Split 2-in-1 Shorts', href: '/products/high-split-grappling-shorts' },
    relatedGuides: ['high-split-vs-standard-grappling-shorts', '2-in-1-grappling-shorts-liner-construction', 'grappling-shorts-waistband-silicone-grip'],
  },
  {
    slug: 'high-split-vs-standard-grappling-shorts',
    title: 'High-Split vs Standard-Split Grappling Shorts',
    description: 'Compare high-split and standard-split grappling shorts for kicking clearance, coverage, silhouette and combat-sport movement.',
    eyebrow: 'GRAPPLING SHORTS FIT GUIDE',
    answer: 'Choose split height from the athlete’s movement and coverage requirements. An ultra-high split maximizes thigh clearance for kicks, shots, sprawls and wide positions; a standard split creates a more conventional outer silhouette. A fitted inner liner can preserve support and coverage beneath a high-split shell.',
    updated: '2026-09-15', cluster: 'grappling-shorts',
    table: [['High-split direction', 'Maximum leg clearance and gladiator-style silhouette'], ['Standard-split direction', 'More conventional outer coverage'], ['Coverage system', 'Review outer opening together with the inner liner'], ['Movement test', 'High kick, shot, sprawl and wide stance'], ['Fit control', 'Waist stability and shell recovery'], ['Approval', 'Sport-specific worn sample']],
    decisionRows: [['Ultra-high split', 'MMA, grappling and movement-led training', 'Confirm opening height and liner coverage'], ['Standard split', 'Buyers preferring a more conventional outer short', 'Check whether the shell restricts the target range'], ['No liner direction', 'Projects requiring a separate base layer', 'Clarify coverage, seam and waistband requirements']],
    notFor: ['Do not select split height from appearance alone.', 'Do not evaluate outer coverage without the intended inner layer.', 'Do not assume one split shape fits every sport or target customer.'],
    source: 'TONTON high-split 2-in-1 sample construction and movement review criteria.',
    sections: [{ heading: 'Start with the required range of motion', paragraphs: ['High kicks, guard entries, shots and wide grappling positions place different demands on the thigh opening. The selected cut should release the leg without making the waistband or remaining shell carry unnecessary tension.'] }, { heading: 'Balance mobility and coverage', paragraphs: ['A deep outer split increases clearance. In a 2-in-1 construction, the fitted liner becomes the coverage layer and should be checked for length, opacity, support and seam comfort.'] }, { heading: 'Record the approval points', bullets: ['Split height and curve', 'Outer-short length', 'Liner length and fit', 'Waistband position', 'Movement result from front, side and rear views'] }],
    relatedProduct: { label: 'View the high-split sample', href: '/products/high-split-grappling-shorts' },
    relatedGuides: ['high-split-grappling-shorts-specifications', '2-in-1-grappling-shorts-liner-construction'],
  },
  {
    slug: '2-in-1-grappling-shorts-liner-construction',
    title: '2-in-1 Grappling Shorts Liner Construction Guide',
    description: 'How to specify a supportive compression liner, outer shell, coverage and custom inner artwork for 2-in-1 grappling shorts.',
    eyebrow: 'GRAPPLING SHORTS CONSTRUCTION GUIDE',
    answer: 'A 2-in-1 grappling short combines a mobile outer shell with a fitted compression liner. The current TONTON high-split sample uses a breathable quick-dry four-way stretch shell and a soft 250gsm milk-silk liner; buyers should confirm liner length, opacity, support, seam comfort and artwork stretch on the physical sample.',
    updated: '2026-09-15', cluster: 'grappling-shorts',
    table: [['Construction', 'Athletic 2-in-1'], ['Outer shell', 'Breathable quick-dry four-way stretch'], ['Verified liner', '250gsm milk-silk on the current high-split sample'], ['Liner purpose', 'Support and coverage beneath the split shell'], ['Customization', 'Approved liner colors, patterns, logos and team artwork'], ['Sample check', 'Length, opacity, seams, recovery and graphic distortion']],
    decisionRows: [['250gsm fitted liner', 'Supportive coverage in the verified high-split sample', 'Check heat, hand feel and compression level'], ['Custom printed liner', 'Brands using the inner layer as a visible design feature', 'Review artwork stretch and placement'], ['Separate compression base', 'Programs not requiring an integrated liner', 'Rebuild the waistband and coverage brief accordingly']],
    notFor: ['Do not treat 250gsm as universal across all shorts.', 'Do not approve liner artwork only from a flat mockup.', 'Do not ignore liner seam placement in high-friction movement zones.'],
    source: 'TONTON High-Split 2-in-1 Grappling Shorts sample with verified 250gsm milk-silk liner.',
    sections: [{ heading: 'Give each layer a clear job', paragraphs: ['The outer shell supplies the athletic silhouette, split mobility and breathable quick-dry direction. The inner liner stays closer to the body to provide support and coverage as the outer layer opens through movement.'] }, { heading: 'Treat the liner as a product, not an accessory', bullets: ['Confirm liner length and leg opening', 'Review compression and recovery', 'Check opacity under movement', 'Inspect seam comfort and attachment at the waist', 'Approve custom graphics at worn stretch'] }, { heading: 'Test the complete two-layer system', paragraphs: ['The layers should move together without bunching, twisting or pulling the waistband. Approve the garment through kicking, stance changes, sprawls and ground transitions.'] }],
    relatedProduct: { label: 'Inspect the 2-in-1 construction', href: '/products/high-split-grappling-shorts' },
    relatedGuides: ['high-split-grappling-shorts-specifications', 'grappling-shorts-waistband-silicone-grip'],
  },
  {
    slug: 'grappling-shorts-waistband-silicone-grip',
    title: 'Grappling Shorts Waistband & Silicone Grip Guide',
    description: 'Plan drawstring adjustment, anti-slip silicone grip, waistband stability and finishing for custom grappling shorts.',
    eyebrow: 'GRAPPLING SHORTS WAIST GUIDE',
    answer: 'A combat-sport waistband should remain stable through rotation, pulling and level changes. The verified high-split sample combines an adjustable drawstring with an interior anti-slip silicone grip strip. Buyers should approve waist pressure, grip, drawstring access, recovery and liner attachment together.',
    updated: '2026-09-15', cluster: 'grappling-shorts',
    table: [['Verified system', 'Adjustable drawstring plus anti-slip silicone grip'], ['Purpose', 'Waist stability during combat movement'], ['Related layer', 'Outer shell and integrated compression liner'], ['Comfort check', 'Pressure, grip feel and skin contact'], ['Construction check', 'Stitching, recovery and liner attachment'], ['Movement test', 'Rotation, shot, sprawl and repeated stance change']],
    decisionRows: [['Drawstring + silicone grip', 'High-movement use requiring two control methods', 'Review pressure and grip on the worn sample'], ['Drawstring-led waist', 'Projects preferring less interior grip', 'Test stability through repeated movement'], ['Branded waistband direction', 'Programs emphasizing visible waist identity', 'Confirm branding does not compromise stretch or adjustment']],
    notFor: ['Do not assume more silicone always means better stability.', 'Do not approve waistband measurements without the attached liner.', 'Do not leave drawstring position and end finishing undefined.'],
    source: 'TONTON high-split grappling shorts waistband sample showing drawstring adjustment and an interior silicone grip strip.',
    sections: [{ heading: 'Build a system around movement', paragraphs: ['The waistband, drawstring, silicone surface and liner attachment work as one system. Stability should be assessed while the athlete rotates, changes level and returns to stance—not only while standing still.'] }, { heading: 'Specify the details buyers can feel', bullets: ['Waist height and finished circumference', 'Drawstring route and access', 'Silicone strip width and position', 'Grip intensity and comfort', 'Liner attachment and reinforced stitching', 'Tagless label placement'] }, { heading: 'Approve security without over-compression', paragraphs: ['The waist should feel secure without excessive pressure. Check whether the silicone catches comfortably, whether the drawstring adjusts evenly and whether the full waistband recovers after training movement.'] }],
    relatedProduct: { label: 'See the verified waistband system', href: '/products/high-split-grappling-shorts' },
    relatedGuides: ['high-split-grappling-shorts-specifications', '2-in-1-grappling-shorts-liner-construction'],
  },
  {
    slug: 'training-shorts-fabric-ventilation-pocket-guide',
    title: 'Training Shorts Fabric, Ventilation & Pocket Guide',
    description: 'A buyer guide to lightweight stretch woven fabric, perforated ventilation, zip pockets, adjustable waistbands and reinforced construction for functional training shorts.',
    eyebrow: 'TRAINING SHORTS BUYER GUIDE',
    answer: 'Functional training shorts should balance movement, airflow, secure storage and waist stability. A practical specification starts with lightweight stretch woven fabric, then defines perforated ventilation, zip-pocket construction, waistband adjustment, crotch mobility and reinforced stitching for the intended gym, HIIT, combat-training or outdoor use.',
    updated: '2026-09-22',
    cluster: 'training-shorts',
    media: [
      { src: '/assets/products/training-shorts-category/ventilation-zip-pocket.webp', alt: 'Training shorts side ventilation and zip pocket detail', caption: 'Real sample detail showing perforated ventilation beside a secure zip pocket.' },
      { src: '/assets/products/training-shorts-category/adjustable-waistband.webp', alt: 'Adjustable waistband construction on functional training shorts', caption: 'Adjustable waistband area with reinforced topstitching.' },
      { src: '/assets/products/training-shorts-category/inner-drawcord-branding.webp', alt: 'Interior drawcord and waistband branding on training shorts', caption: 'Interior adjustment and branding details that should be confirmed on the sample.' },
    ],
    table: [
      ['Fabric direction', 'Lightweight polyester- or nylon-based stretch woven performance fabric'],
      ['Movement', 'Confirm lateral and recovery stretch for squats, lunges and kicks'],
      ['Ventilation', 'Perforated side detail; hole method and edge stability require confirmation'],
      ['Storage', 'Secure side zip pocket for small items'],
      ['Waist control', 'Elastic and adjustable construction; confirm drawcord or tab route'],
      ['Use direction', 'Gym, HIIT, functional fitness, combat training and outdoor activity'],
    ],
    decisionRows: [
      ['Polyester stretch woven', 'Quick-dry training programs and custom color directions', 'Confirm composition, weight, recovery and abrasion performance'],
      ['Nylon stretch woven', 'Buyers prioritizing a smooth hand feel and abrasion direction', 'Confirm actual composition and colorfastness before claiming performance'],
      ['Perforation + zip pocket', 'Multi-use training shorts needing airflow and secure storage', 'Check hole-edge stability, pocket bag, zipper and skin contact'],
    ],
    notFor: ['Do not call a zip pocket waterproof unless its zipper, seam and pocket construction have been verified.', 'Do not publish a fabric composition or GSM until it belongs to the selected approved style.', 'Do not assume a utility training short automatically meets combat-sport competition rules.'],
    source: 'TONTON functional training shorts sample details covering ventilation, zip-pocket, waistband and reinforced construction review.',
    sections: [
      { heading: 'Start with movement and recovery', paragraphs: ['The shell should release the hips and thighs during squats, lunges, jumps and kicking drills, then recover without bagging. Confirm stretch direction and finished-garment mobility together.'] },
      { heading: 'Specify ventilation and storage as constructions', bullets: ['Define perforation position, spacing and edge quality', 'Confirm zipper type, opening length and puller direction', 'Inspect pocket-bag depth and attachment', 'Check whether internal components rub during movement', 'Record reinforcement at the pocket ends and high-load seams'] },
      { heading: 'Approve the intended use honestly', paragraphs: ['This direction suits gym, HIIT, cross-training, combat conditioning and light outdoor use. Competition eligibility and water resistance require separate evidence and should not be inferred from appearance.'] },
    ],
    faqs: [
      ['What fabric is suitable for functional training shorts?', 'A lightweight stretch woven polyester or nylon direction is common, but composition, GSM, stretch and recovery should be confirmed on the selected sample.'],
      ['Are perforated holes the same as mesh panels?', 'No. Perforation creates openings in a panel, while mesh is a separate open-structure material. Each requires different edge and seam checks.'],
      ['Can these shorts be used for MMA training?', 'They can suit conditioning, bag work and general combat training, but formal competition or grappling use should be confirmed against equipment rules and real wear testing.'],
    ],
    relatedProduct: { label: 'Explore custom Training Shorts', href: '/customization/sublimated-training-shorts' },
    relatedGuides: ['fightwear-quality-inspection-checklist', 'custom-fightwear-sampling-moq'],
  },
  {
    slug: 'fightwear-quality-inspection-checklist',
    title: 'Custom Fightwear Quality Inspection Checklist',
    description: 'A practical QC checklist for custom Rash Guards and fight shorts covering material, print, measurements, seams, waist systems, labels and packing.',
    eyebrow: 'QUALITY CONTROL GUIDE',
    answer: 'A useful fightwear inspection compares the finished order with the approved sample and specification. Check material identity, color and print placement, measurements, stretch seams, waist and closure systems, labels, workmanship and packing using recorded tolerances and an agreed sampling plan.',
    updated: '2026-09-22',
    cluster: 'project',
    media: [
      { src: '/assets/process/03-stitching-size-inspection.webp', alt: 'TONTON staff inspecting garment stitching and measurements', caption: 'Stitching, construction and measurement checks against the approved specification.' },
      { src: '/assets/process/03-finished-garment-qc.webp', alt: 'TONTON quality control inspection of finished custom sportswear', caption: 'Finished-garment review before packing and order handover.' },
      { src: '/assets/process/04-folding-packing.webp', alt: 'Finished custom sportswear being folded and packed', caption: 'Packing review after final product checks are completed.' },
    ],
    table: [
      ['Reference', 'Approved sample, artwork and product specification'],
      ['Material', 'Composition/weight where confirmed, hand feel, color and stretch direction'],
      ['Construction', 'Seams, reinforcement, waistband, closure, liner and hems'],
      ['Branding', 'Artwork scale, placement, color direction, labels and logo finish'],
      ['Measurements', 'Agreed points of measure and tolerances across requested sizes'],
      ['Packing', 'Labels, folding, bagging, quantity and carton requirements'],
    ],
    decisionRows: [
      ['Pre-production approval', 'New products, fits, materials and artwork', 'Freeze the sample and specification before bulk work'],
      ['In-line inspection', 'Orders needing process checks before completion', 'Confirm checkpoints, quantity stage and issue escalation'],
      ['Final inspection', 'Finished orders before packing or shipment', 'Use the agreed sampling plan, tolerances and packing brief'],
    ],
    notFor: ['A checklist does not replace product-specific tolerances and an approved sample.', 'Do not claim a laboratory result without a corresponding test report.', 'Do not accept appearance-only inspection where size, stretch, closure or seam function matters.'],
    source: 'TONTON production workflow covering print, stitching, measurement, finished-garment QC and packing review.',
    sections: [
      { heading: 'Freeze the inspection reference', paragraphs: ['Before inspection begins, identify the approved sample, artwork version, size specification, labels, packaging and any accepted revisions. A checklist without a controlled reference cannot prove conformity.'] },
      { heading: 'Inspect product-specific risk points', bullets: ['Rash Guard opacity, recovery, stretch seams and lower-hem control', 'Fight-short waistband, drawstring, hook-and-loop closure and split reinforcement', '2-in-1 liner length, opacity, seam comfort and attachment', 'Print alignment, logo position and visible color variation', 'Skipped stitches, open seams, puckering and loose thread'] },
      { heading: 'Record issues for corrective action', paragraphs: ['Record the affected style, size, defect location, quantity and severity. Recheck corrected goods against the same approved reference before packing or shipment.'] },
    ],
    faqs: [
      ['What should be used as the main QC reference?', 'Use the approved sample together with the latest artwork, measurement specification, construction notes, labels and packing requirements.'],
      ['Is final inspection enough for a new product?', 'Not always. New materials, prints or constructions may benefit from pre-production and in-line checks so issues are found before the order is complete.'],
      ['Should every product use the same checklist?', 'The inspection framework can be shared, but risk points and tolerances must be adjusted for each product and approved specification.'],
    ],
    relatedProduct: { label: 'Review TONTON factory and QC', href: '/factory' },
    relatedGuides: ['custom-fightwear-sampling-moq', 'prepare-artwork-for-sublimation', 'flatlock-vs-overlock-rash-guard-seams'],
  },
  {
    slug: 'prepare-artwork-for-sublimation',
    title: 'How to Prepare Artwork for Sublimation',
    description: 'Prepare logos, colors, panel artwork and approval notes for custom sublimated Rash Guards, fight shorts and teamwear.',
    eyebrow: 'SUBLIMATION ARTWORK GUIDE',
    answer: 'Prepare sublimation artwork by supplying vector logos where available, naming brand colors, separating priority and secondary marks, identifying placement by garment panel and noting any alignment requirement across seams. Final production artwork should be confirmed on the supplier template and approved through a mockup and physical sample.',
    updated: '2026-09-22',
    cluster: 'project',
    media: [
      { src: '/assets/process/01-project-brief-design.webp', alt: 'Designer preparing custom sportswear artwork and product layout', caption: 'Artwork and layout preparation before the production file is finalized.' },
      { src: '/assets/process/01-requirements-confirmation.webp', alt: 'TONTON team confirming custom product design requirements', caption: 'Product, logo, color and construction requirements are confirmed as one brief.' },
      { src: '/assets/process/02-sublimation-printing.webp', alt: 'Sublimation printing process for custom sportswear panels', caption: 'Approved artwork moves into the sublimation printing stage before cutting and sewing.' },
    ],
    table: [
      ['Preferred logo input', 'Vector AI, EPS, SVG or editable PDF where available'],
      ['Raster references', 'Supply the highest available resolution at intended use size'],
      ['Color direction', 'Provide Pantone or brand references when color matching matters'],
      ['Placement map', 'Identify front, back, sleeve, side and waistband positions'],
      ['Panel control', 'Confirm bleed, seam crossings, alignment and safe zones on the supplier template'],
      ['Approval route', 'Mockup review followed by physical sample confirmation'],
    ],
    decisionRows: [
      ['Vector logo', 'Scalable sponsor and brand marks', 'Check outlines, transparency and the approved color reference'],
      ['High-resolution raster art', 'Textures and photographic-style graphics', 'Confirm resolution at production size and panel bleed'],
      ['Panel-to-panel artwork', 'Designs that visually continue across seams', 'Set alignment expectations and review size grading on the mockup'],
    ],
    notFor: ['Do not assume a low-resolution screenshot can be enlarged cleanly for production.', 'Do not treat screen color as proof of printed color; confirm the physical sample.', 'Do not place critical text or small marks on seam allowances or high-distortion zones.'],
    source: 'TONTON design-confirmation and sublimation workflow from project brief through artwork layout, print and sample review.',
    sections: [
      { heading: 'Send an organized artwork package', bullets: ['Separate logos from visual references', 'Name each mark and intended position', 'Identify mandatory brand colors', 'List priority, secondary and optional artwork', 'Provide editable files and font information where permitted'] },
      { heading: 'Design around garment panels', paragraphs: ['Sublimation is applied to panels before the garment is sewn. Important text, faces, small sponsor marks and alignment features need safe space from seam allowances and high-stretch zones.'] },
      { heading: 'Approve both mockup and physical result', paragraphs: ['The mockup controls layout and hierarchy. The sample confirms printed color direction, scale, seam interaction and how artwork appears on the worn garment. Record every accepted revision before bulk production.'] },
    ],
    faqs: [
      ['Do I need final artwork before requesting a quote?', 'No. A product direction, logos and references can start the discussion, but production-ready artwork is required before print approval.'],
      ['Which logo format is best for sublimation?', 'Vector AI, EPS, SVG or editable PDF is preferred because it can scale cleanly. High-resolution raster files may work for suitable graphics.'],
      ['Why can printed color differ from a monitor?', 'Screens emit light while fabric printing depends on ink, material, heat and viewing conditions. Approve critical colors on a physical sample.'],
    ],
    relatedProduct: { label: 'Start a structured artwork brief', href: '/project-builder' },
    relatedGuides: ['rash-guard-sublimation-logo-placement', 'custom-fightwear-sampling-moq', 'fightwear-quality-inspection-checklist'],
  },
  {
    slug: 'custom-fightwear-sampling-moq',
    title: 'Custom Fightwear Sampling & MOQ Guide',
    description: 'A practical guide to preparing artwork, specifications, samples and quantity information for a custom fightwear project.',
    eyebrow: 'OEM / ODM PROJECT GUIDE',
    answer: 'Start with the product type, estimated quantity, intended use, size range, artwork status and destination market. The applicable MOQ, sample route and production timing are confirmed after the selected product, material and construction requirements are reviewed.',
    updated: '2026-09-15',
    cluster: 'project',
    table: [
      ['Starting information', 'Product, quantity, use, sizes, artwork and destination'],
      ['MOQ', 'Confirmed for the selected product, quantity and specification'],
      ['Mockup', 'Artwork, color and logo placement review'],
      ['Sample review', 'Fit, material, construction, branding and workmanship'],
      ['Bulk approval', 'Begins against the approved sample and specification'],
      ['Schedule', 'Confirmed for the specific project after review'],
    ],
    decisionRows: [
      ['Digital mockup first', 'Projects still resolving artwork, color and logo placement', 'Provide vector logos and visual references where available'],
      ['Physical sample review', 'New fits, materials, construction or private-label programs', 'Record the approved fit, color, material, seams and branding'],
      ['Repeat specification', 'Reorders based on an already approved product', 'Identify the previous specification and list every requested change'],
    ],
    notFor: [
      'Do not treat one MOQ as universal across different products, materials and specifications.',
      'A digital mockup cannot replace physical checks for fit, hand feel, opacity or construction.',
      'Do not set a production schedule before material, artwork, quantity and packaging are reviewed.',
    ],
    source: 'TONTON OEM/ODM project briefing, mockup, sample-approval and bulk-production workflow.',
    sections: [
      { heading: 'What to prepare before requesting a quote', bullets: ['Product type and estimated quantity', 'Target users and intended sport', 'Required sizes and fit direction', 'Vector logo or available artwork', 'Reference product and construction priorities', 'Destination country and preferred contact method'] },
      { heading: 'Why MOQ and timing are project-specific', paragraphs: ['Materials, printing method, construction, size assortment, artwork readiness and packaging can change the production route. A supplier should confirm the schedule and applicable MOQ against the actual brief instead of treating one number as universal.'] },
      { heading: 'What the approved sample controls', paragraphs: ['The approved sample is the practical reference for fit, color direction, material, artwork placement, seam construction, labels and other confirmed details before bulk work begins.'] },
    ],
    faqs: [
      ['Is one MOQ used for every custom fightwear product?', 'No. The applicable MOQ depends on the selected product, material, construction, artwork, quantity mix and project requirements.'],
      ['Can a digital mockup replace a physical sample?', 'A mockup helps approve layout, but it cannot confirm fit, hand feel, opacity, stretch, seam comfort or finished workmanship.'],
      ['What information is needed to start?', 'Provide the product type, estimated quantity, intended use, sizes, artwork status, destination and any construction priorities.'],
    ],
    relatedProduct: { label: 'Build a structured project brief', href: '/project-builder' },
    relatedGuides: ['prepare-artwork-for-sublimation', 'fightwear-quality-inspection-checklist', 'training-shorts-fabric-ventilation-pocket-guide'],
  },
];

export function getResource(slug: string) {
  return RESOURCE_PAGES.find((resource) => resource.slug === slug);
}
